# Generated by Django 3.1.7 on 2021-04-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_infected_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_locations',
            name='infected',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='infected_user',
        ),
    ]
