# Generated by Django 3.1.7 on 2021-04-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210410_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='infected',
            field=models.BooleanField(default=False),
        ),
    ]
