# Generated by Django 3.1.7 on 2021-04-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='img1',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='polls',
            name='img2',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='polls',
            name='img3',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='polls',
            name='img4',
            field=models.URLField(blank=True),
        ),
    ]
