# Generated by Django 3.1.7 on 2021-04-08 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polling', '0002_auto_20210408_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='name3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='polls',
            name='name4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='polls',
            name='vote3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='polls',
            name='vote4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='my_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.JSONField(default={})),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
