# Generated by Django 3.1.7 on 2021-04-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0003_auto_20210409_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_vote',
            name='votes',
            field=models.JSONField(default=dict),
        ),
    ]
